spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scryfall
    username: scryfall-user
    password: scryfall-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


scryfall:
  url: https://api.scryfall.com/